services:
  portfoliowebsite:
    build:
      context: ./PortfolioWebsite        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
    ports:
      - "3002:3002"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=3002
    networks:
      - backend

  whatstheword:
    build:
      context: ./WhatsTheWordApp        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        REACT_APP_BASE_BACKEND_URL: "http://localhost/"
        REACT_APP_WEBSOCKET_PATH: "/whatstheword/socket.io/"
        BACKEND_URL: ${WHATSTHEWORD_PUBLIC_URL}
    ports:
      - "5002:5002"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=5002
    networks:
      - backend

  stockpapertrading:
    build:
      context: ./StockPaperTradingApp      
      dockerfile: Dockerfile   
      args:
        REACT_APP_BACKEND_URL: "http://localhost/stockpapertrading"
        BACKEND_URL: ${STOCKPAPERTRADING_PUBLIC_URL}
    ports:
      - "8002:8002"             
    restart: always            
    environment:
      PORT: 8002
      DATABASE_URL: ${STOCKPAPERTRADING_DATABASE_URL}
      API_KEY: ${STOCKPAPERTRADING_API_KEY}
      JWT_ENCRIPTION_KEY: ${STOCKPAPERTRADING_JWT_ENCRIPTION_KEY}
      ENV: ${ENV}
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - backend

  mealsy:
    build:
      context: ./Mealsy       
      dockerfile: Dockerfile  
      args:
        APP_NAME: ${MEALSY_APP_NAME}
        ENV: ${MEALSY_ENV}
    command: sh -c "npx prisma migrate deploy && node app.js"
    ports:
      - "7002:7002"            
    restart: always         
    environment:
      PORT: 7002
      DATABASE_URL: ${MEALSY_DATABASE_URL}
      JWT_SECRET: ${MEALSY_JWT_SECRET}
      JWT_LIFETIME: ${MEALSY_JWT_LIFETIME}
      API_KEY: ${MEALSY_API_KEY}
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - backend

  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432" # OPTIONAL (for local access from your machine)
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahmoudagag"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DOMAIN_NAME: ${NGINX_DOMAIN_NAME}
    depends_on:
      - whatstheword
      - portfoliowebsite
      - stockpapertrading
      - mealsy
    networks:
      - backend
  
volumes:
  pgdata:
  
networks:
  backend:
    driver: bridge
### ASL/ 

# to build: docker compose up --build