services:
  portfoliowebsite:
    build:
      context: ./PortfolioWebsite        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        - REACT_APP_BACKEND_URL=http://localhost
        - REACT_APP_PORTFOLIOWEBSITE_PORT=3000
        - REACT_APP_WHATSTHEWORDAPP_PORT=5000
    ports:
      - "3000:3000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=3000

  whatstheword:
    build:
      context: ./WhatsTheWordApp        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        - REACT_APP_BACKEND_URL=http://localhost:5000/
    ports:
      - "5000:5000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=5000