services:
  portfoliowebsite-backend:
    # container_name: PortfolioWebsite-backend
    build:
      context: ./PortfolioWebsite/backend        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
    ports:
      - "3000:3000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=3000

  portfoliowebsite-frontend:
    # container_name: PortfolioWebsite-frontend
    build:
      context: ./PortfolioWebsite/frontend        # Path to the Dockerfile for the frontend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'  
      args:
        - REACT_APP_BACKEND_URL=http://localhost
        - REACT_APP_PORTFOLIOWEBSITE_PORT=3000
        - REACT_APP_WHATSTHEWORDAPP_PORT=5000
    ports:
      - "80:80"                 # Expose frontend's port 80
    restart: always             # Restart policy

# # What's the word
  whatstheword-backend:
    # container_name: WhatsTheWord-backend
    build:
      context: ./WhatsTheWordApp/backend        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
    ports:
      - "3001:3001"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=3001

  whatstheword-frontend:
    # container_name: WhatsTheWord-frontend
    build:
      context: ./WhatsTheWordApp/frontend       # Path to the Dockerfile for the frontend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'  
      args:
        - REACT_APP_BACKEND_URL=http://localhost:3001/
    ports:
      - "5000:5000"                 # Expose frontend's port 80
    restart: always             # Restart policy
