services:
  portfoliowebsite:
    image: 952027539394.dkr.ecr.us-east-1.amazonaws.com/portfoliowebsite
    ports:
      - "3002:3002" 
    restart: always
    environment:
      - PORT=3002
    networks:
      - backend

  whatstheword:
    image: 952027539394.dkr.ecr.us-east-1.amazonaws.com/whatstheword
    ports:
      - "5002:5002"
    restart: always
    environment:
      - PORT=5002
    networks:
      - backend

  stockpapertrading:
    image: 952027539394.dkr.ecr.us-east-1.amazonaws.com/stockpapertrading 
    ports:
      - "8002:8002"             
    restart: always            
    environment:
      PORT: 8002
      DATABASE_URL: ${STOCKPAPERTRADING_DATABASE_URL}
      API_KEY: ${STOCKPAPERTRADING_API_KEY}
      JWT_ENCRIPTION_KEY: ${STOCKPAPERTRADING_JWT_ENCRIPTION_KEY}
      ENV: ${ENV}
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - backend

  mealsy:
    image: 952027539394.dkr.ecr.us-east-1.amazonaws.com/mealsy
    command: sh -c "npx prisma migrate deploy && node app.js"
    ports:
      - "7002:7002"            
    restart: always         
    environment:
      PORT: 7002
      DATABASE_URL: ${MEALSY_DATABASE_URL}
      JWT_SECRET: ${MEALSY_JWT_SECRET}
      JWT_LIFETIME: ${MEALSY_JWT_LIFETIME}
      API_KEY: ${MEALSY_API_KEY}
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - backend

  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432" # OPTIONAL (for local access from your machine)
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahmoudagag"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: 952027539394.dkr.ecr.us-east-1.amazonaws.com/nginx-portfolio
    ports:
      - "80:80"
    depends_on:
      - whatstheword
      - portfoliowebsite
      - stockpapertrading
      - mealsy
    networks:
      - backend
  
volumes:
  pgdata:
  
networks:
  backend:
    driver: bridge