services:
  portfoliowebsite:
    build:
      context: ./PortfolioWebsite        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        # - REACT_APP_BACKEND_URL=http://localhost
        - REACT_APP_BACKEND_URL=54.162.204.24
        - REACT_APP_PORTFOLIOWEBSITE_PORT=3000
        - REACT_APP_WHATSTHEWORDAPP_PORT=5000
        - REACT_APP_STOCKPAPERTRADINGAPP_PORT=8000
        - REACT_APP_MEALSYAPP_PORT=7000
    ports:
      - "3000:3000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=3000

  whatstheword:
    build:
      context: ./WhatsTheWordApp        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        # - REACT_APP_BACKEND_URL=http://localhost:5000/
        - REACT_APP_BACKEND_URL=54.162.204.24:5000/
    ports:
      - "5000:5000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=5000

  stockpapertrading:
    build:
      context: ./StockPaperTradingApp       # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        # - REACT_APP_BACKEND_URL=http://localhost:8000
        - REACT_APP_BACKEND_URL=54.162.204.24:8000
        - MONGODB_URI=mongodb+srv://agagmahmoud:xGiowF7dffBIZmPa@cluster0.xrrtozz.mongodb.net/?retryWrites=true&w=majority
        - API_KEY=iQmewMFHJY7lz3iha1WrBazQaikCkTZ45iGInxOW
        - JWT_ENCRIPTION_KEY=FkdcFb5Dsa
    ports:
      - "8000:8000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=8000

  measly:
    build:
      context: ./Mealsy        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        # - REACT_APP_BACKEND_URL=http://localhost:7000
        - REACT_APP_BACKEND_URL=54.162.204.24:7000
        - MONGO_URL=mongodb+srv://agagmahmoud:xGiowF7dffBIZmPa@cluster0.xrrtozz.mongodb.net/?retryWrites=true&w=majority
        - JWT_SECRET=BC5kVNZjOF
        - JWT_LIFETIME=1d
        - API_KEY=j1SvC0/dlV9huEqfruyNRA==iWtoDdyERSYTsHXN
    ports:
      - "7000:7000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=7000

### ASL/ 