# Use the official Nginx image as the base
FROM nginx:latest

# Copy your custom Nginx config into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to be accessible from outside the container
EXPOSE 80